spring:
  data:
    neo4j:
      uri: ${GRAPHENEDB_BOLT_URL}
      username: ${GRAPHENEDB_BOLT_USER}
      password: ${GRAPHENEDB_BOLT_PASSWORD}
slack:
  bot:
    token: ${SLACK_TOKEN}
    verification: ${SLACK_VERIFICATION}